# -*- coding: utf-8 -*-

iso3166_1 = [
    ( u"Afghanistan"                                          , u"AF"                            , u"AFG" , u"004"   , u"ISO 3166-2:AF" ),
    ( u"Åland Islands"                                        , u"AX"                            , u"ALA" , u"248"   , u"ISO 3166-2:AX" ),
    ( u"Albania"                                              , u"AL"                            , u"ALB" , u"008"   , u"ISO 3166-2:AL" ),
    ( u"Algeria"                                              , u"DZ"                            , u"DZA" , u"012"   , u"ISO 3166-2:DZ" ),
    ( u"American Samoa"                                       , u"AS"                            , u"ASM" , u"016"   , u"ISO 3166-2:AS" ),
    ( u"Andorra"                                              , u"AD"                            , u"AND" , u"020"   , u"ISO 3166-2:AD" ),
    ( u"Angola"                                               , u"AO"                            , u"AGO" , u"024"   , u"ISO 3166-2:AO" ),
    ( u"Anguilla"                                             , u"AI"                            , u"AIA" , u"660"   , u"ISO 3166-2:AI" ),
    ( u"Antarctica"                                           , u"AQ"                            , u"ATA" , u"010"   , u"ISO 3166-2:AQ" ),
    ( u"Antigua and Barbuda"                                  , u"AG"                            , u"ATG" , u"028"   , u"ISO 3166-2:AG" ),
    ( u"Argentina"                                            , u"AR"                            , u"ARG" , u"032"   , u"ISO 3166-2:AR" ),
    ( u"Armenia"                                              , u"AM"                            , u"ARM" , u"051"   , u"ISO 3166-2:AM" ),
    ( u"Aruba"                                                , u"AW"                            , u"ABW" , u"533"   , u"ISO 3166-2:AW" ),
    ( u"Australia"                                            , u"AU"                            , u"AUS" , u"036"   , u"ISO 3166-2:AU" ),
    ( u"Austria"                                              , u"AT"                            , u"AUT" , u"040"   , u"ISO 3166-2:AT" ),
    ( u"Azerbaijan"                                           , u"AZ"                            , u"AZE" , u"031"   , u"ISO 3166-2:AZ" ),
    ( u"Bahamas"                                              , u"BS"                            , u"BHS" , u"044"   , u"ISO 3166-2:BS" ),
    ( u"Bahrain"                                              , u"BH"                            , u"BHR" , u"048"   , u"ISO 3166-2:BH" ),
    ( u"Bangladesh"                                           , u"BD"                            , u"BGD" , u"050"   , u"ISO 3166-2:BD" ),
    ( u"Barbados"                                             , u"BB"                            , u"BRB" , u"052"   , u"ISO 3166-2:BB" ),
    ( u"Belarus"                                              , u"BY"                            , u"BLR" , u"112"   , u"ISO 3166-2:BY" ),
    ( u"Belgium"                                              , u"BE"                            , u"BEL" , u"056"   , u"ISO 3166-2:BE" ),
    ( u"Belize"                                               , u"BZ"                            , u"BLZ" , u"084"   , u"ISO 3166-2:BZ" ),
    ( u"Benin"                                                , u"BJ"                            , u"BEN" , u"204"   , u"ISO 3166-2:BJ" ),
    ( u"Bermuda"                                              , u"BM"                            , u"BMU" , u"060"   , u"ISO 3166-2:BM" ),
    ( u"Bhutan"                                               , u"BT"                            , u"BTN" , u"064"   , u"ISO 3166-2:BT" ),
    ( u"Bolivia (Plurinational State of)"                     , u"BO"                            , u"BOL" , u"068"   , u"ISO 3166-2:BO" ),
    ( u"Bonaire, Sint Eustatius and Saba"                     , u"BQ"                            , u"BES" , u"535"   , u"ISO 3166-2:BQ" ),
    ( u"Bosnia and Herzegovina"                               , u"BA"                            , u"BIH" , u"070"   , u"ISO 3166-2:BA" ),
    ( u"Botswana"                                             , u"BW"                            , u"BWA" , u"072"   , u"ISO 3166-2:BW" ),
    ( u"Bouvet Island"                                        , u"BV"                            , u"BVT" , u"074"   , u"ISO 3166-2:BV" ),
    ( u"Brazil"                                               , u"BR"                            , u"BRA" , u"076"   , u"ISO 3166-2:BR" ),
    ( u"British Indian Ocean Territory"                       , u"IO"                            , u"IOT" , u"086"   , u"ISO 3166-2:IO" ),
    ( u"Brunei Darussalam"                                    , u"BN"                            , u"BRN" , u"096"   , u"ISO 3166-2:BN" ),
    ( u"Bulgaria"                                             , u"BG"                            , u"BGR" , u"100"   , u"ISO 3166-2:BG" ),
    ( u"Burkina Faso"                                         , u"BF"                            , u"BFA" , u"854"   , u"ISO 3166-2:BF" ),
    ( u"Burundi"                                              , u"BI"                            , u"BDI" , u"108"   , u"ISO 3166-2:BI" ),
    ( u"Cabo Verde"                                           , u"CV"                            , u"CPV" , u"132"   , u"ISO 3166-2:CV" ),
    ( u"Cambodia"                                             , u"KH"                            , u"KHM" , u"116"   , u"ISO 3166-2:KH" ),
    ( u"Cameroon"                                             , u"CM"                            , u"CMR" , u"120"   , u"ISO 3166-2:CM" ),
    ( u"Canada"                                               , u"CA"                            , u"CAN" , u"124"   , u"ISO 3166-2:CA" ),
    ( u"Cayman Islands"                                       , u"KY"                            , u"CYM" , u"136"   , u"ISO 3166-2:KY" ),
    ( u"Central African Republic"                             , u"CF"                            , u"CAF" , u"140"   , u"ISO 3166-2:CF" ),
    ( u"Chad"                                                 , u"TD"                            , u"TCD" , u"148"   , u"ISO 3166-2:TD" ),
    ( u"Chile"                                                , u"CL"                            , u"CHL" , u"152"   , u"ISO 3166-2:CL" ),
    ( u"China"                                                , u"CN"                            , u"CHN" , u"156"   , u"ISO 3166-2:CN" ),
    ( u"Christmas Island"                                     , u"CX"                            , u"CXR" , u"162"   , u"ISO 3166-2:CX" ),
    ( u"Cocos (Keeling) Islands"                              , u"CC"                            , u"CCK" , u"166"   , u"ISO 3166-2:CC" ),
    ( u"Colombia"                                             , u"CO"                            , u"COL" , u"170"   , u"ISO 3166-2:CO" ),
    ( u"Comoros"                                              , u"KM"                            , u"COM" , u"174"   , u"ISO 3166-2:KM" ),
    ( u"Congo"                                                , u"CG"                            , u"COG" , u"178"   , u"ISO 3166-2:CG" ),
    ( u"Congo, Democratic Republic of the"                    , u"CD"                            , u"COD" , u"180"   , u"ISO 3166-2:CD" ),
    ( u"Cook Islands"                                         , u"CK"                            , u"COK" , u"184"   , u"ISO 3166-2:CK" ),
    ( u"Costa Rica"                                           , u"CR"                            , u"CRI" , u"188"   , u"ISO 3166-2:CR" ),
    ( u"Côte d'Ivoire"                                        , u"CI"                            , u"CIV" , u"384"   , u"ISO 3166-2:CI" ),
    ( u"Croatia"                                              , u"HR"                            , u"HRV" , u"191"   , u"ISO 3166-2:HR" ),
    ( u"Cuba"                                                 , u"CU"                            , u"CUB" , u"192"   , u"ISO 3166-2:CU" ),
    ( u"Curaçao"                                              , u"CW"                            , u"CUW" , u"531"   , u"ISO 3166-2:CW" ),
    ( u"Cyprus"                                               , u"CY"                            , u"CYP" , u"196"   , u"ISO 3166-2:CY" ),
    ( u"Czechia"                                              , u"CZ"                            , u"CZE" , u"203"   , u"ISO 3166-2:CZ" ),
    ( u"Denmark"                                              , u"DK"                            , u"DNK" , u"208"   , u"ISO 3166-2:DK" ),
    ( u"Djibouti"                                             , u"DJ"                            , u"DJI" , u"262"   , u"ISO 3166-2:DJ" ),
    ( u"Dominica"                                             , u"DM"                            , u"DMA" , u"212"   , u"ISO 3166-2:DM" ),
    ( u"Dominican Republic"                                   , u"DO"                            , u"DOM" , u"214"   , u"ISO 3166-2:DO" ),
    ( u"Ecuador"                                              , u"EC"                            , u"ECU" , u"218"   , u"ISO 3166-2:EC" ),
    ( u"Egypt"                                                , u"EG"                            , u"EGY" , u"818"   , u"ISO 3166-2:EG" ),
    ( u"El Salvador"                                          , u"SV"                            , u"SLV" , u"222"   , u"ISO 3166-2:SV" ),
    ( u"Equatorial Guinea"                                    , u"GQ"                            , u"GNQ" , u"226"   , u"ISO 3166-2:GQ" ),
    ( u"Eritrea"                                              , u"ER"                            , u"ERI" , u"232"   , u"ISO 3166-2:ER" ),
    ( u"Estonia"                                              , u"EE"                            , u"EST" , u"233"   , u"ISO 3166-2:EE" ),
    ( u"Eswatini"                                             , u"SZ"                            , u"SWZ" , u"748"   , u"ISO 3166-2:SZ" ),
    ( u"Ethiopia"                                             , u"ET"                            , u"ETH" , u"231"   , u"ISO 3166-2:ET" ),
    ( u"Falkland Islands (Malvinas)"                          , u"FK"                            , u"FLK" , u"238"   , u"ISO 3166-2:FK" ),
    ( u"Faroe Islands"                                        , u"FO"                            , u"FRO" , u"234"   , u"ISO 3166-2:FO" ),
    ( u"Fiji"                                                 , u"FJ"                            , u"FJI" , u"242"   , u"ISO 3166-2:FJ" ),
    ( u"Finland"                                              , u"FI"                            , u"FIN" , u"246"   , u"ISO 3166-2:FI" ),
    ( u"France"                                               , u"FR"                            , u"FRA" , u"250"   , u"ISO 3166-2:FR" ),
    ( u"French Guiana"                                        , u"GF"                            , u"GUF" , u"254"   , u"ISO 3166-2:GF" ),
    ( u"French Polynesia"                                     , u"PF"                            , u"PYF" , u"258"   , u"ISO 3166-2:PF" ),
    ( u"French Southern Territories"                          , u"TF"                            , u"ATF" , u"260"   , u"ISO 3166-2:TF" ),
    ( u"Gabon"                                                , u"GA"                            , u"GAB" , u"266"   , u"ISO 3166-2:GA" ),
    ( u"Gambia"                                               , u"GM"                            , u"GMB" , u"270"   , u"ISO 3166-2:GM" ),
    ( u"Georgia"                                              , u"GE"                            , u"GEO" , u"268"   , u"ISO 3166-2:GE" ),
    ( u"Germany"                                              , u"DE"                            , u"DEU" , u"276"   , u"ISO 3166-2:DE" ),
    ( u"Ghana"                                                , u"GH"                            , u"GHA" , u"288"   , u"ISO 3166-2:GH" ),
    ( u"Gibraltar"                                            , u"GI"                            , u"GIB" , u"292"   , u"ISO 3166-2:GI" ),
    ( u"Greece"                                               , u"GR"                            , u"GRC" , u"300"   , u"ISO 3166-2:GR" ),
    ( u"Greenland"                                            , u"GL"                            , u"GRL" , u"304"   , u"ISO 3166-2:GL" ),
    ( u"Grenada"                                              , u"GD"                            , u"GRD" , u"308"   , u"ISO 3166-2:GD" ),
    ( u"Guadeloupe"                                           , u"GP"                            , u"GLP" , u"312"   , u"ISO 3166-2:GP" ),
    ( u"Guam"                                                 , u"GU"                            , u"GUM" , u"316"   , u"ISO 3166-2:GU" ),
    ( u"Guatemala"                                            , u"GT"                            , u"GTM" , u"320"   , u"ISO 3166-2:GT" ),
    ( u"Guernsey"                                             , u"GG"                            , u"GGY" , u"831"   , u"ISO 3166-2:GG" ),
    ( u"Guinea"                                               , u"GN"                            , u"GIN" , u"324"   , u"ISO 3166-2:GN" ),
    ( u"Guinea-Bissau"                                        , u"GW"                            , u"GNB" , u"624"   , u"ISO 3166-2:GW" ),
    ( u"Guyana"                                               , u"GY"                            , u"GUY" , u"328"   , u"ISO 3166-2:GY" ),
    ( u"Haiti"                                                , u"HT"                            , u"HTI" , u"332"   , u"ISO 3166-2:HT" ),
    ( u"Heard Island and McDonald Islands"                    , u"HM"                            , u"HMD" , u"334"   , u"ISO 3166-2:HM" ),
    ( u"Holy See"                                             , u"VA"                            , u"VAT" , u"336"   , u"ISO 3166-2:VA" ),
    ( u"Honduras"                                             , u"HN"                            , u"HND" , u"340"   , u"ISO 3166-2:HN" ),
    ( u"Hong Kong"                                            , u"HK"                            , u"HKG" , u"344"   , u"ISO 3166-2:HK" ),
    ( u"Hungary"                                              , u"HU"                            , u"HUN" , u"348"   , u"ISO 3166-2:HU" ),
    ( u"Iceland"                                              , u"IS"                            , u"ISL" , u"352"   , u"ISO 3166-2:IS" ),
    ( u"India"                                                , u"IN"                            , u"IND" , u"356"   , u"ISO 3166-2:IN" ),
    ( u"Indonesia"                                            , u"ID"                            , u"IDN" , u"360"   , u"ISO 3166-2:ID" ),
    ( u"Iran (Islamic Republic of)"                           , u"IR"                            , u"IRN" , u"364"   , u"ISO 3166-2:IR" ),
    ( u"Iraq"                                                 , u"IQ"                            , u"IRQ" , u"368"   , u"ISO 3166-2:IQ" ),
    ( u"Ireland"                                              , u"IE"                            , u"IRL" , u"372"   , u"ISO 3166-2:IE" ),
    ( u"Isle of Man"                                          , u"IM"                            , u"IMN" , u"833"   , u"ISO 3166-2:IM" ),
    ( u"Israel"                                               , u"IL"                            , u"ISR" , u"376"   , u"ISO 3166-2:IL" ),
    ( u"Italy"                                                , u"IT"                            , u"ITA" , u"380"   , u"ISO 3166-2:IT" ),
    ( u"Jamaica"                                              , u"JM"                            , u"JAM" , u"388"   , u"ISO 3166-2:JM" ),
    ( u"Japan"                                                , u"JP"                            , u"JPN" , u"392"   , u"ISO 3166-2:JP" ),
    ( u"Jersey"                                               , u"JE"                            , u"JEY" , u"832"   , u"ISO 3166-2:JE" ),
    ( u"Jordan"                                               , u"JO"                            , u"JOR" , u"400"   , u"ISO 3166-2:JO" ),
    ( u"Kazakhstan"                                           , u"KZ"                            , u"KAZ" , u"398"   , u"ISO 3166-2:KZ" ),
    ( u"Kenya"                                                , u"KE"                            , u"KEN" , u"404"   , u"ISO 3166-2:KE" ),
    ( u"Kiribati"                                             , u"KI"                            , u"KIR" , u"296"   , u"ISO 3166-2:KI" ),
    ( u"Korea (Democratic People's Republic of)"              , u"KP"                            , u"PRK" , u"408"   , u"ISO 3166-2:KP" ),
    ( u"Korea, Republic of"                                   , u"KR"                            , u"KOR" , u"410"   , u"ISO 3166-2:KR" ),
    ( u"Kuwait"                                               , u"KW"                            , u"KWT" , u"414"   , u"ISO 3166-2:KW" ),
    ( u"Kyrgyzstan"                                           , u"KG"                            , u"KGZ" , u"417"   , u"ISO 3166-2:KG" ),
    ( u"Lao People's Democratic Republic"                     , u"LA"                            , u"LAO" , u"418"   , u"ISO 3166-2:LA" ),
    ( u"Latvia"                                               , u"LV"                            , u"LVA" , u"428"   , u"ISO 3166-2:LV" ),
    ( u"Lebanon"                                              , u"LB"                            , u"LBN" , u"422"   , u"ISO 3166-2:LB" ),
    ( u"Lesotho"                                              , u"LS"                            , u"LSO" , u"426"   , u"ISO 3166-2:LS" ),
    ( u"Liberia"                                              , u"LR"                            , u"LBR" , u"430"   , u"ISO 3166-2:LR" ),
    ( u"Libya"                                                , u"LY"                            , u"LBY" , u"434"   , u"ISO 3166-2:LY" ),
    ( u"Liechtenstein"                                        , u"LI"                            , u"LIE" , u"438"   , u"ISO 3166-2:LI" ),
    ( u"Lithuania"                                            , u"LT"                            , u"LTU" , u"440"   , u"ISO 3166-2:LT" ),
    ( u"Luxembourg"                                           , u"LU"                            , u"LUX" , u"442"   , u"ISO 3166-2:LU" ),
    ( u"Macao"                                                , u"MO"                            , u"MAC" , u"446"   , u"ISO 3166-2:MO" ),
    ( u"Madagascar"                                           , u"MG"                            , u"MDG" , u"450"   , u"ISO 3166-2:MG" ),
    ( u"Malawi"                                               , u"MW"                            , u"MWI" , u"454"   , u"ISO 3166-2:MW" ),
    ( u"Malaysia"                                             , u"MY"                            , u"MYS" , u"458"   , u"ISO 3166-2:MY" ),
    ( u"Maldives"                                             , u"MV"                            , u"MDV" , u"462"   , u"ISO 3166-2:MV" ),
    ( u"Mali"                                                 , u"ML"                            , u"MLI" , u"466"   , u"ISO 3166-2:ML" ),
    ( u"Malta"                                                , u"MT"                            , u"MLT" , u"470"   , u"ISO 3166-2:MT" ),
    ( u"Marshall Islands"                                     , u"MH"                            , u"MHL" , u"584"   , u"ISO 3166-2:MH" ),
    ( u"Martinique"                                           , u"MQ"                            , u"MTQ" , u"474"   , u"ISO 3166-2:MQ" ),
    ( u"Mauritania"                                           , u"MR"                            , u"MRT" , u"478"   , u"ISO 3166-2:MR" ),
    ( u"Mauritius"                                            , u"MU"                            , u"MUS" , u"480"   , u"ISO 3166-2:MU" ),
    ( u"Mayotte"                                              , u"YT"                            , u"MYT" , u"175"   , u"ISO 3166-2:YT" ),
    ( u"Mexico"                                               , u"MX"                            , u"MEX" , u"484"   , u"ISO 3166-2:MX" ),
    ( u"Micronesia (Federated States of)"                     , u"FM"                            , u"FSM" , u"583"   , u"ISO 3166-2:FM" ),
    ( u"Moldova, Republic of"                                 , u"MD"                            , u"MDA" , u"498"   , u"ISO 3166-2:MD" ),
    ( u"Monaco"                                               , u"MC"                            , u"MCO" , u"492"   , u"ISO 3166-2:MC" ),
    ( u"Mongolia"                                             , u"MN"                            , u"MNG" , u"496"   , u"ISO 3166-2:MN" ),
    ( u"Montenegro"                                           , u"ME"                            , u"MNE" , u"499"   , u"ISO 3166-2:ME" ),
    ( u"Montserrat"                                           , u"MS"                            , u"MSR" , u"500"   , u"ISO 3166-2:MS" ),
    ( u"Morocco"                                              , u"MA"                            , u"MAR" , u"504"   , u"ISO 3166-2:MA" ),
    ( u"Mozambique"                                           , u"MZ"                            , u"MOZ" , u"508"   , u"ISO 3166-2:MZ" ),
    ( u"Myanmar"                                              , u"MM"                            , u"MMR" , u"104"   , u"ISO 3166-2:MM" ),
    ( u"Namibia"                                              , u"NA"                            , u"NAM" , u"516"   , u"ISO 3166-2:NA" ),
    ( u"Nauru"                                                , u"NR"                            , u"NRU" , u"520"   , u"ISO 3166-2:NR" ),
    ( u"Nepal"                                                , u"NP"                            , u"NPL" , u"524"   , u"ISO 3166-2:NP" ),
    ( u"Netherlands"                                          , u"NL"                            , u"NLD" , u"528"   , u"ISO 3166-2:NL" ),
    ( u"New Caledonia"                                        , u"NC"                            , u"NCL" , u"540"   , u"ISO 3166-2:NC" ),
    ( u"New Zealand"                                          , u"NZ"                            , u"NZL" , u"554"   , u"ISO 3166-2:NZ" ),
    ( u"Nicaragua"                                            , u"NI"                            , u"NIC" , u"558"   , u"ISO 3166-2:NI" ),
    ( u"Niger"                                                , u"NE"                            , u"NER" , u"562"   , u"ISO 3166-2:NE" ),
    ( u"Nigeria"                                              , u"NG"                            , u"NGA" , u"566"   , u"ISO 3166-2:NG" ),
    ( u"Niue"                                                 , u"NU"                            , u"NIU" , u"570"   , u"ISO 3166-2:NU" ),
    ( u"Norfolk Island"                                       , u"NF"                            , u"NFK" , u"574"   , u"ISO 3166-2:NF" ),
    ( u"North Macedonia"                                      , u"MK"                            , u"MKD" , u"807"   , u"ISO 3166-2:MK" ),
    ( u"Northern Mariana Islands"                             , u"MP"                            , u"MNP" , u"580"   , u"ISO 3166-2:MP" ),
    ( u"Norway"                                               , u"NO"                            , u"NOR" , u"578"   , u"ISO 3166-2:NO" ),
    ( u"Oman"                                                 , u"OM"                            , u"OMN" , u"512"   , u"ISO 3166-2:OM" ),
    ( u"Pakistan"                                             , u"PK"                            , u"PAK" , u"586"   , u"ISO 3166-2:PK" ),
    ( u"Palau"                                                , u"PW"                            , u"PLW" , u"585"   , u"ISO 3166-2:PW" ),
    ( u"Palestine, State of"                                  , u"PS"                            , u"PSE" , u"275"   , u"ISO 3166-2:PS" ),
    ( u"Panama"                                               , u"PA"                            , u"PAN" , u"591"   , u"ISO 3166-2:PA" ),
    ( u"Papua New Guinea"                                     , u"PG"                            , u"PNG" , u"598"   , u"ISO 3166-2:PG" ),
    ( u"Paraguay"                                             , u"PY"                            , u"PRY" , u"600"   , u"ISO 3166-2:PY" ),
    ( u"Peru"                                                 , u"PE"                            , u"PER" , u"604"   , u"ISO 3166-2:PE" ),
    ( u"Philippines"                                          , u"PH"                            , u"PHL" , u"608"   , u"ISO 3166-2:PH" ),
    ( u"Pitcairn"                                             , u"PN"                            , u"PCN" , u"612"   , u"ISO 3166-2:PN" ),
    ( u"Poland"                                               , u"PL"                            , u"POL" , u"616"   , u"ISO 3166-2:PL" ),
    ( u"Portugal"                                             , u"PT"                            , u"PRT" , u"620"   , u"ISO 3166-2:PT" ),
    ( u"Puerto Rico"                                          , u"PR"                            , u"PRI" , u"630"   , u"ISO 3166-2:PR" ),
    ( u"Qatar"                                                , u"QA"                            , u"QAT" , u"634"   , u"ISO 3166-2:QA" ),
    ( u"Réunion"                                              , u"RE"                            , u"REU" , u"638"   , u"ISO 3166-2:RE" ),
    ( u"Romania"                                              , u"RO"                            , u"ROU" , u"642"   , u"ISO 3166-2:RO" ),
    ( u"Russian Federation"                                   , u"RU"                            , u"RUS" , u"643"   , u"ISO 3166-2:RU" ),
    ( u"Rwanda"                                               , u"RW"                            , u"RWA" , u"646"   , u"ISO 3166-2:RW" ),
    ( u"Saint Barthélemy"                                     , u"BL"                            , u"BLM" , u"652"   , u"ISO 3166-2:BL" ),
    ( u"Saint Helena, Ascension and Tristan da Cunha"         , u"SH"                            , u"SHN" , u"654"   , u"ISO 3166-2:SH" ),
    ( u"Saint Kitts and Nevis"                                , u"KN"                            , u"KNA" , u"659"   , u"ISO 3166-2:KN" ),
    ( u"Saint Lucia"                                          , u"LC"                            , u"LCA" , u"662"   , u"ISO 3166-2:LC" ),
    ( u"Saint Martin (French part)"                           , u"MF"                            , u"MAF" , u"663"   , u"ISO 3166-2:MF" ),
    ( u"Saint Pierre and Miquelon"                            , u"PM"                            , u"SPM" , u"666"   , u"ISO 3166-2:PM" ),
    ( u"Saint Vincent and the Grenadines"                     , u"VC"                            , u"VCT" , u"670"   , u"ISO 3166-2:VC" ),
    ( u"Samoa"                                                , u"WS"                            , u"WSM" , u"882"   , u"ISO 3166-2:WS" ),
    ( u"San Marino"                                           , u"SM"                            , u"SMR" , u"674"   , u"ISO 3166-2:SM" ),
    ( u"Sao Tome and Principe"                                , u"ST"                            , u"STP" , u"678"   , u"ISO 3166-2:ST" ),
    ( u"Saudi Arabia"                                         , u"SA"                            , u"SAU" , u"682"   , u"ISO 3166-2:SA" ),
    ( u"Senegal"                                              , u"SN"                            , u"SEN" , u"686"   , u"ISO 3166-2:SN" ),
    ( u"Serbia"                                               , u"RS"                            , u"SRB" , u"688"   , u"ISO 3166-2:RS" ),
    ( u"Seychelles"                                           , u"SC"                            , u"SYC" , u"690"   , u"ISO 3166-2:SC" ),
    ( u"Sierra Leone"                                         , u"SL"                            , u"SLE" , u"694"   , u"ISO 3166-2:SL" ),
    ( u"Singapore"                                            , u"SG"                            , u"SGP" , u"702"   , u"ISO 3166-2:SG" ),
    ( u"Sint Maarten (Dutch part)"                            , u"SX"                            , u"SXM" , u"534"   , u"ISO 3166-2:SX" ),
    ( u"Slovakia"                                             , u"SK"                            , u"SVK" , u"703"   , u"ISO 3166-2:SK" ),
    ( u"Slovenia"                                             , u"SI"                            , u"SVN" , u"705"   , u"ISO 3166-2:SI" ),
    ( u"Solomon Islands"                                      , u"SB"                            , u"SLB" , u"090"   , u"ISO 3166-2:SB" ),
    ( u"Somalia"                                              , u"SO"                            , u"SOM" , u"706"   , u"ISO 3166-2:SO" ),
    ( u"South Africa"                                         , u"ZA"                            , u"ZAF" , u"710"   , u"ISO 3166-2:ZA" ),
    ( u"South Georgia and the South Sandwich Islands"         , u"GS"                            , u"SGS" , u"239"   , u"ISO 3166-2:GS" ),
    ( u"South Sudan"                                          , u"SS"                            , u"SSD" , u"728"   , u"ISO 3166-2:SS" ),
    ( u"Spain"                                                , u"ES"                            , u"ESP" , u"724"   , u"ISO 3166-2:ES" ),
    ( u"Sri Lanka"                                            , u"LK"                            , u"LKA" , u"144"   , u"ISO 3166-2:LK" ),
    ( u"Sudan"                                                , u"SD"                            , u"SDN" , u"729"   , u"ISO 3166-2:SD" ),
    ( u"Suriname"                                             , u"SR"                            , u"SUR" , u"740"   , u"ISO 3166-2:SR" ),
    ( u"Svalbard and Jan Mayen"                               , u"SJ"                            , u"SJM" , u"744"   , u"ISO 3166-2:SJ" ),
    ( u"Sweden"                                               , u"SE"                            , u"SWE" , u"752"   , u"ISO 3166-2:SE" ),
    ( u"Switzerland"                                          , u"CH"                            , u"CHE" , u"756"   , u"ISO 3166-2:CH" ),
    ( u"Syrian Arab Republic"                                 , u"SY"                            , u"SYR" , u"760"   , u"ISO 3166-2:SY" ),
    ( u"Taiwan, Province of China[a]"                         , u"TW"                            , u"TWN" , u"158"   , u"ISO 3166-2:TW" ),
    ( u"Tajikistan"                                           , u"TJ"                            , u"TJK" , u"762"   , u"ISO 3166-2:TJ" ),
    ( u"Tanzania, United Republic of"                         , u"TZ"                            , u"TZA" , u"834"   , u"ISO 3166-2:TZ" ),
    ( u"Thailand"                                             , u"TH"                            , u"THA" , u"764"   , u"ISO 3166-2:TH" ),
    ( u"Timor-Leste"                                          , u"TL"                            , u"TLS" , u"626"   , u"ISO 3166-2:TL" ),
    ( u"Togo"                                                 , u"TG"                            , u"TGO" , u"768"   , u"ISO 3166-2:TG" ),
    ( u"Tokelau"                                              , u"TK"                            , u"TKL" , u"772"   , u"ISO 3166-2:TK" ),
    ( u"Tonga"                                                , u"TO"                            , u"TON" , u"776"   , u"ISO 3166-2:TO" ),
    ( u"Trinidad and Tobago"                                  , u"TT"                            , u"TTO" , u"780"   , u"ISO 3166-2:TT" ),
    ( u"Tunisia"                                              , u"TN"                            , u"TUN" , u"788"   , u"ISO 3166-2:TN" ),
    ( u"Turkey"                                               , u"TR"                            , u"TUR" , u"792"   , u"ISO 3166-2:TR" ),
    ( u"Turkmenistan"                                         , u"TM"                            , u"TKM" , u"795"   , u"ISO 3166-2:TM" ),
    ( u"Turks and Caicos Islands"                             , u"TC"                            , u"TCA" , u"796"   , u"ISO 3166-2:TC" ),
    ( u"Tuvalu"                                               , u"TV"                            , u"TUV" , u"798"   , u"ISO 3166-2:TV" ),
    ( u"Uganda"                                               , u"UG"                            , u"UGA" , u"800"   , u"ISO 3166-2:UG" ),
    ( u"Ukraine"                                              , u"UA"                            , u"UKR" , u"804"   , u"ISO 3166-2:UA" ),
    ( u"United Arab Emirates"                                 , u"AE"                            , u"ARE" , u"784"   , u"ISO 3166-2:AE" ),
    ( u"United Kingdom of Great Britain and Northern Ireland" , u"GB"                            , u"GBR" , u"826"   , u"ISO 3166-2:GB" ),
    ( u"United States of America"                             , u"US"                            , u"USA" , u"840"   , u"ISO 3166-2:US" ),
    ( u"United States Minor Outlying Islands"                 , u"UM"                            , u"UMI" , u"581"   , u"ISO 3166-2:UM" ),
    ( u"Uruguay"                                              , u"UY"                            , u"URY" , u"858"   , u"ISO 3166-2:UY" ),
    ( u"Uzbekistan"                                           , u"UZ"                            , u"UZB" , u"860"   , u"ISO 3166-2:UZ" ),
    ( u"Vanuatu"                                              , u"VU"                            , u"VUT" , u"548"   , u"ISO 3166-2:VU" ),
    ( u"Venezuela (Bolivarian Republic of)"                   , u"VE"                            , u"VEN" , u"862"   , u"ISO 3166-2:VE" ),
    ( u"Viet Nam"                                             , u"VN"                            , u"VNM" , u"704"   , u"ISO 3166-2:VN" ),
    ( u"Virgin Islands (British)"                             , u"VG"                            , u"VGB" , u"092"   , u"ISO 3166-2:VG" ),
    ( u"Virgin Islands (U.S.)"                                , u"VI"                            , u"VIR" , u"850"   , u"ISO 3166-2:VI" ),
    ( u"Wallis and Futuna"                                    , u"WF"                            , u"WLF" , u"876"   , u"ISO 3166-2:WF" ),
    ( u"Western Sahara"                                       , u"EH"                            , u"ESH" , u"732"   , u"ISO 3166-2:EH" ),
    ( u"Yemen"                                                , u"YE"                            , u"YEM" , u"887"   , u"ISO 3166-2:YE" ),
    ( u"Zambia"                                               , u"ZM"                            , u"ZMB" , u"894"   , u"ISO 3166-2:ZM" ),
    ( u"Zimbabwe"                                             , u"ZW"                            , u"ZWE" , u"716"   , u"ISO 3166-2:ZW" ),
]
